version: '3'
services:
  dcard_demo_redis:
    container_name: dcard_demo_redis
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - dcard_demo_docker_network
  dcard_demo_mysql:
    container_name: dcard_demo_mysql
    restart: always
    image: mariadb:10.3
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=circleci
      - MYSQL_DATABASE=mouWorks
    networks:
      - dcard_demo_docker_network

networks:
  dcard_demo_docker_network: